export const patientFormDefaultValues = {
  fullname: "",
  email: "",
  phone: "",
  birthDate: "",
  gender: "",
  address: "",
  profession: "",
  civilStatus: "",
  phoneNumberAlt: "",
  healthInsurance: "",
  healthInsuranceNumber: "",
  allergies: "",
  currentMedicines: "",
  familyMedicalHistory: "",
  pastFamilyMedicalHistory: "",
  idType: "DNI",
  idNumber: "",
  idPhoto: [],
  treatmentConsent: false,
  disclosureConsent: false,
  privacyConsent: false,
};
